# remind后端部署服务
name: deploy

env:
  REMIND_TARGET_DIR: '/data/actions-runner/_work/Remind/Remind/target'
  SERVICE_NAME: 'remind'

# push触发
# 绑定master分支
on:
  push:
    branches: [ main ]

# 构建步骤
jobs:
  # 编译
  excute:
    # 指定运行环境 self-hosted 标签来选择任何自托管运行器 linux为附属标签
    runs-on: [self-hosted, Linux, X64]

    # 步骤
    steps:
      # 检出代码
      # 这个是官方的用于拉取代码的actions
      # `@` 后面可以跟指定的分支或者 release 的版本或者特定的commit
      - name: checkout
        #这里用官方的action了，阿里云和GITHUB通信有问题，可能会拉不到代码
        uses: actions/checkout@main
      #        with:	# 当前 actions 的一些配置 需要2.8以上git支持
      #          submodules: true # 如果项目有依赖 Git 子项目时可以设为 true，拉取的时候会一并拉取下来

      # 编译
      - name: build
        run: |
          echo 'start build ......'
          mvn clean install -Dmaven.test.skip=true
          mkdir -p /data/$SERVICE_NAME
          echo 'build success'

      - name: deploy
        run: |
          echo 'start deploy ......'
          docker build -t remind .
          echo 'deploy success'